name: amazonka-dynamodb-test
version: 0.1.0.0
github: "githubuser/amazonka-dynamodb-test"
license: BSD3
author: "Author name here"
maintainer: "example@example.com"
copyright: "2021 Author name here"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/amazonka-dynamodb-test#readme>

dependencies:
  - base >= 4.7 && < 5
  - amazonka-core
  - amazonka-dynamodb
  - amazonka
  - dynamodb-simple
  - lens
  - aeson
  - ghc-prim
  - unordered-containers
  - text
  - unliftio-core
  - safe-exceptions

library:
  source-dirs: src

executables:
  amazonka-dynamodb-test-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wall
      - -Werror
    dependencies:
      - amazonka-dynamodb-test

tests:
  amazonka-dynamodb-test-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - amazonka-dynamodb-test
